---
title: "Development Process"
output:
  rmarkdown::html_vignette
    
vignette: >
  %\VignetteIndexEntry{Development Process}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Once you’ve familiarized yourself with the `{datacutr}` [contribution
model](contribution_model.html) and you’re ready to make your first code
contribution, this development process step-by-step guide will help tie all the
other detailed vignettes together to give you the simplest experience of helping
to grow and enhance our codebase.

1. To start, you will have either created an issue or commented on an existing
issue to notify that you’d like to contribute code. Then one of the `{datacutr}`
core team will assign you to the issue.
1. Create a new feature branch from the development branch `devel` following the naming convention and pull the latest changes - as detailed on the [github usage](git_usage.html#working-with-feature-branches-1) guide.
1. Familiarize yourself with the `{datacutr}` [programming
strategy](programming_strategy.html), and then make the required code updates.
1. Before making a pull request, check the [Pull Request Review Guidance](pr_review_guidance.html) & the following checklist of common things developers miss:
    a. Is all your code formatted according to the [tidyverse](https://style.tidyverse.org/) style guide?
    a. Did you create/add appropriate [unit tests](unit_test_guidance.html#writing-unit-tests-in-admiral-)?
    a. If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](programming_strategy.html#deprecation-1)?
    a. Did you update the [documentation](programming_strategy.html#function-header-documentation-)? If so, remember to run `devtools::document()` and include the updated `NAMESPACE` and `.Rd` files in `man/` 
    a. Does your code update have any impact on the R scripts stored in `inst/templates`?
    a. Does your code update have any impact on the vignettes stored in vignettes?
    a. Did you update the Changelog `NEWS.md`?
    a. Did you build `{datacutr}` site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](../reference/index.html)" page?
1. Once happy with all the updates, make a [pull request](git_usage.html#pull-request) to merge to the development branch `devel` and link the issue so that it closes after successful merging.
1. Check that there are no merge conflicts. If there are any, fix them before requesting review. See [solving merge conflicts](git_usage.html#solving-merge-conflicts-in-the-terminal-on-rstudio) guidance.
1. Check the results of the automated `R-CMD check` and `lintr` checks and if any issues consult this [guide](pr_review_guidance.html#common-r-cmd-check-issues-1).
1. Assign a reviewer from the `{datacutr}` core development team – this could be
anyone you discussed the issue with previously via Slack or GitHub. 
1. Once the review is completed, the reviewer will merge the PR and this will then automatically delete the feature branch.

Don't hesitate to reach out for
support via the `{datacutr}` Slack channel (link to be added). **Welcome to our
`{datacutr}` community!**_
