---
title: "FAQ"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 6
vignette: >
  %\VignetteIndexEntry{FAQ}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

##### **What is datacutr**?


##### **Why** did we decide to start **datacutr**?


##### Why did we use **R as a programming language**?

 * R is not an isolated software product, everyone can contribute (open source principal)
 * People from University/Statistical talent pipeline more likely to come through with R skills rather than a proprietary language 
 * There seems to be a strong data science/analytics R community
 * FDA open to accepting R submissions and are heavy users themselves
 * Top of the line visualization/graphics - R-Shiny for interactive data displays and also R Markdown offers great report writing functionality
 * R is very popular among statisticians so new statistical methods are likely implemented in R before any other language
 * There might be equally suited programming languages out there - however at some stage we had to make a decision :)
 
##### Why do we use a **certain R version and package versions** for development?

* The choice of R Version is not set in stone.  However, a common development environment is important to establish when working across multiple companies and multiple developers. We currently work in R Version 3.6.3, but that will change as we move forward with `{datacutr}`. This need for a common development environment also carries over for our choice of package versions.  
* GitHub allows us through the Actions/Workflows to test `{datacutr}` under several versions of R as well as several versions of dependent R packages needed for `{datacutr}`.  Currently we test `{datacutr}` against R Version 3.6.3 with a CRAN package snapshot from 2020-02-29, R Version 4.0 with a CRAN package snapshot from 2021-03-31 and the latest R version with the latest snapshots of packages.  You can view this workflow on our [GitHub Repository](https://github.com/pharmaverse/datacutr/blob/main/.github/workflows/R-CMD-check.yml).
* This common development allows us to easily re-create bugs and provide solutions to each other issues that developers will encounter.
* Reviewers of Pull Requests when running code will know that their environment is identical to the initiator of the Pull Request.  This ensures faster review times and higher quality Pull Request reviews.
* We achieve this common development environment by using a **lockfile** created from the [`renv`](https://rstudio.github.io/renv/) package. New developers will encounter a suggested `renv::restore()` in the console to revert or move forward your R version and package versions.

##### How does a user **know what a function does** exactly?

* Function details and its purpose, the requirements, parameters, dependencies and examples are documented in the header of each function.
* Complex functions potentially have a vignette on the `{datacutr}` homepage to provide more details. 

##### In **which order** does a user need to execute the functions?

* Guidance will be provided in the template scripts.

##### Is the `{datacutr}`  package **validated**?

 * All functions  are reviewed and tested (see [What will be provided around **function testing**?]) to ensure that  they  work as described in the documentation. 
 * Test  cases for each function  will  be part of the R package.
 * Users can add to the  tests or provide additional feedback.
 * The  testing the `{datacutr}` team will do for each function does **not replace the QC and validation process at each company**.
 * A [GitHub action](https://github.com/marketplace/actions/r-package-validation-report) (using open source packages) exists to generate a validation report for an R package, which would be an option for any company to use. 

##### What will be provided around **function testing**?

 * Unit tests for reliability of each function - available as part of open source release
 * Guidance for testing and documentation expectations of community contribution functions. Then it is for each company to cover the following:
   * validation to be able to use the package on company-specific SCE for GxP purposes and associated audit evidence 
   * strategy of how the use of `{datacutr}` fits into company-specific quality assurance process
   * see our guidance on [unit testing](unit_test_guidance.html)

##### Will there be a user/**contribution** guide?

 * Our [programming strategy](programming_strategy.html) serves as a framework
 for users how to create their own functions. 
 * Please see the [contribution model website](contribution_model.html) for a detailed description how to contribute

